name: flash
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  libadwaita: ^1.2.1
  adwaita: ^0.5.2
  libadwaita_bitsdojo: ^0.5.5
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  meta: ^1.7.0
  adwaita_icons: ^0.2.1
  bloc: ^8.1.0
  equatable: ^2.0.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  generate: true
