name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"
    name: "Release"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install dependencies for Flutter Linux toolchain
        run: sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Flutter doctor
        run: flutter doctor
      - name: Build AppImage
        run: make build-appimage
      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: Flash-x86_64.AppImage
